#!/usr/bin/env bash
set -euo pipefail

echo "==> Check formatting"
nix fmt -- --check .
echo "==> Evaluate flake outputs and NixOS hosts"
nix flake check --all-systems --no-build
echo "==> Evaluate Mac"
nix eval --raw .#darwinConfigurations.mac.system.drvPath
