{
  cfg,
  lib,
}: let
  inherit (lib) concatMapStringsSep concatStringsSep listToAttrs nameValuePair;

  luaString = s:
    "\""
    + (builtins.replaceStrings
      ["\\" "\"" "\n" "\r" "\t"]
      ["\\\\" "\\\"" "\\n" "\\r" "\\t"]
      s)
    + "\"";

  # ---- Render a Nix value as a Lua literal expression ----
  toLua = v:
    if v == null
    then "nil"
    else if builtins.isBool v
    then
      if v
      then "true"
      else "false"
    else if builtins.isInt v || builtins.isFloat v
    then toString v
    else if builtins.isString v
    then luaString v
    else if builtins.isList v
    then "{" + concatStringsSep ", " (map toLua v) + "}"
    else if builtins.isAttrs v
    then
      "{"
      + concatStringsSep ", " (map
        (k: let
          val = v.${k};
          key =
            if builtins.match "[a-zA-Z_][a-zA-Z0-9_]*" k != null
            then k
            else "[${luaString k}]";
        in "${key} = ${toLua val}")
        (builtins.attrNames v))
      + "}"
    else throw "toLua: unsupported value: ${builtins.toJSON v}";

  initModule =
    ''
      -- Hyprland 0.55+ Lua config. See:
      --   https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua
      --   https://github.com/hyprwm/Hyprland/blob/main/meta/hl.meta.lua
      -- This file is generated by modules/home/hyprland/lua.nix. The local Lua
      -- modules live under modules/home/hyprland/lua/.

      local cfg = ${toLua cfg}
      local ctx = { hl = hl, cfg = cfg }
    ''
    + concatMapStringsSep "\n" (name: ''
      require(${luaString name})(ctx)
    '')
    moduleNames;

  # Each file returns function(ctx), then the generated config executes it.
  # Order is still meaningful: desktop and commands define local policy tables,
  # state tracks runtime modes, cheatsheet tracks sidecar state,
  # bind-helpers decorates direct hl.bind calls,
  # cheatsheet.events follows compositor submap truth, runtime modules register
  # event handlers, binds registers top-level shortcuts, and binds/submaps
  # consumes the helper-domain modules.
  luaModule = name: path: {inherit name path;};
  luaModuleFromName = name: luaModule name ((builtins.replaceStrings ["."] ["/"] name) + ".lua");

  initModules = [
    (luaModuleFromName "desktop")
    (luaModuleFromName "commands")
    (luaModuleFromName "state")
    (luaModuleFromName "cheatsheet")
    (luaModuleFromName "bind-helpers")
    (luaModuleFromName "workspace-layout")
    (luaModuleFromName "cheatsheet.events")
    (luaModuleFromName "window-state")
    (luaModuleFromName "special-apps")
    (luaModuleFromName "external-monitor-workspaces")
    (luaModuleFromName "smart-focus")
    (luaModuleFromName "window-policy")
    (luaModuleFromName "rules")
    (luaModuleFromName "state-watchers")
    (luaModuleFromName "hyprbars")
    (luaModuleFromName "special-workspaces")
    (luaModuleFromName "sunshine")
    (luaModuleFromName "autostart")
    (luaModuleFromName "binds")
    (luaModuleFromName "binds.submaps")
  ];

  optionalModules = [
    (luaModuleFromName "binds.groups")
    (luaModuleFromName "binds.layouts.master")
    (luaModuleFromName "binds.layouts.hy3")
    (luaModuleFromName "binds.layouts.scrolling")
    (luaModuleFromName "binds.submaps.core")
    (luaModuleFromName "binds.submaps.emacs")
    (luaModuleFromName "binds.submaps.tmux")
  ];

  modules = initModules ++ optionalModules;

  moduleNames = map (module: module.name) initModules;
  moduleFile = module:
    nameValuePair module.name {
      content = ./lua + "/${module.path}";
      autoLoad = false;
    };
in
  {
    "00-init" = {
      content = initModule;
      autoLoad = true;
    };
  }
  // listToAttrs (map moduleFile modules)
