{
  cfg,
  lib,
}: let
  inherit (lib) concatMapStringsSep concatStringsSep;

  luaString = s:
    "\""
    + (builtins.replaceStrings
      ["\\" "\"" "\n" "\r" "\t"]
      ["\\\\" "\\\"" "\\n" "\\r" "\\t"]
      s)
    + "\"";

  # ---- Render a Nix value as a Lua literal expression ----
  toLua = v:
    if v == null
    then "nil"
    else if builtins.isBool v
    then
      if v
      then "true"
      else "false"
    else if builtins.isInt v || builtins.isFloat v
    then toString v
    else if builtins.isString v
    then luaString v
    else if builtins.isList v
    then "{" + concatStringsSep ", " (map toLua v) + "}"
    else if builtins.isAttrs v
    then
      "{"
      + concatStringsSep ", " (map
        (k: let
          val = v.${k};
          key =
            if builtins.match "[a-zA-Z_][a-zA-Z0-9_]*" k != null
            then k
            else "[${luaString k}]";
        in "${key} = ${toLua val}")
        (builtins.attrNames v))
      + "}"
    else throw "toLua: unsupported value: ${builtins.toJSON v}";

  cfgPrelude = ''
    -- Hyprland 0.55+ Lua config. See:
    --   https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua
    --   https://github.com/hyprwm/Hyprland/blob/main/meta/hl.meta.lua
    -- This file is generated by modules/home/hyprland/lua.nix from the .lua
    -- chunks under modules/home/hyprland/lua/. Edit the .lua files, not the
    -- rendered output.

    local cfg = ${toLua cfg}
    local ctx = { hl = hl, cfg = cfg }
  '';

  # Each file returns function(ctx), then the generated config executes it.
  # Order is still meaningful: helpers populates ctx, config registers static
  # Hyprland settings, smart-focus exports ctx.smartFocus, rules registers
  # window/autostart behavior, and binds consumes the helpers.
  files = [
    "helpers.lua"
    "config.lua"
    "external-monitor-workspaces.lua"
    "smart-focus.lua"
    "rules.lua"
    "binds.lua"
  ];

  renderModule = f: ''
    do
        local module = (function()
    ${builtins.readFile (./lua + "/${f}")}
        end)()
        module(ctx)
    end
  '';
in
  cfgPrelude + "\n" + concatMapStringsSep "\n" renderModule files
