{
  cfg,
  commands,
  settings,
  lib,
}: let
  inherit (lib) concatMapStringsSep listToAttrs nameValuePair;
  toLua = lib.generators.toLua {multiline = false;};

  initModule =
    ''
      -- Hyprland 0.55+ Lua config. See:
      --   https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua
      -- LuaLS stubs come from the active Hyprland package:
      --   $out/share/hypr/stubs/hl.meta.lua
      -- This file is generated by modules/home/hyprland/lua.nix. The local Lua
      -- modules live under modules/home/hyprland/lua/.

      local ctx = { hl = hl }
    ''
    + concatMapStringsSep "\n" (module: ''
      require(${toLua module.name})(ctx, ${toLua (module.args or {})})
    '')
    initModules;

  # Each file returns function(ctx, opts). Order is still meaningful: state must
  # exist before dispatch/state consumers, and helpers must exist before HM's
  # generated bind/submap calls run later in hyprland.lua.
  luaModule = name: path: args: {inherit name path args;};
  luaModuleFromName = name: luaModule name ((builtins.replaceStrings ["."] ["/"] name) + ".lua");
  luaModuleWithArgs = name: args: luaModuleFromName name args;
  stateNames = [
    "gaming"
    "idle"
    "locked"
    "streaming"
    "remote-streaming"
    "double"
    "screen-recording"
    "do-not-disturb"
  ];
  statePriority = [
    "locked"
    "remote-streaming"
    "streaming"
    "double"
    "screen-recording"
    "gaming"
    "do-not-disturb"
    "idle"
  ];
  userClearStates = [
    "do-not-disturb"
  ];
  layoutPresets = {
    gapless = {
      general = {
        gaps_out = 0;
        gaps_in = 0;
      };
      decoration.rounding = 0;
      group.groupbar = {
        rounding = 0;
        gradient_rounding = 0;
      };
    };
    default = {
      general = {
        inherit (settings.general) gaps_out gaps_in;
      };
      decoration = {
        inherit (settings.decoration) rounding;
      };
      group.groupbar = {
        inherit (settings.group.groupbar) rounding gradient_rounding;
      };
    };
  };

  initModules =
    [
      (luaModuleWithArgs "state" {
        states = stateNames;
        priority = statePriority;
        clearUser = userClearStates;
        publisher = commands.statePublish;
      })
      (luaModuleWithArgs "dispatch" {
        presets = layoutPresets;
      })
      (luaModuleWithArgs "next-window" {
        timeoutMs = 5 * 60 * 1000;
      })
      (luaModuleWithArgs "terminal" {
        terminal = commands.terminalBin;
        fallback = commands.terminal;
        remoteControl = cfg.terminalBackend == "kitty";
      })
      (luaModuleWithArgs "window-state" {})
      (luaModuleWithArgs "monitor-policy" {
        inherit (cfg) desktop;
        stream = cfg.sunshine.stream;
      })
      (luaModuleWithArgs "external-monitor-workspaces" {
        inherit (cfg) desktop;
      })
      (luaModuleWithArgs "smart-focus" {
        features = {
          inherit (cfg.features) emacs neovim;
        };
        apps = {
          kitty = commands.kittyBin;
          jq = commands.jqBin;
          nvim = commands.nvimBin;
          emacsclient = commands.emacsclientBin;
          timeout = commands.timeoutBin;
          tmux = commands.tmuxBin;
        };
        inherit (cfg) smartFocus;
      })
      (luaModuleWithArgs "state-watchers" {})
      (luaModuleWithArgs "monitor-states" {
        inherit (cfg) desktop;
        stream = cfg.sunshine.stream;
        hyprctl = commands.hyprctlBin;
        debounceMs = 180;
        retryMs = 250;
        recoveryMs = 5000;
        retryTicks = 4;
        maxAttempts = 3;
      })
      (luaModuleWithArgs "sunshine" {
        enable = cfg.sunshine.enable;
      })
    ]
    ++ lib.optionals cfg.features.emacs [
      (luaModuleWithArgs "emacs" {
        raise = commands.emacsRaise;
      })
    ];

  modules = initModules;

  moduleFile = module:
    nameValuePair module.name {
      content = ./lua + "/${module.path}";
      autoLoad = false;
    };
in
  {
    "00-init" = {
      content = initModule;
      autoLoad = true;
    };
  }
  // listToAttrs (map moduleFile modules)
