{
  lib,
  config,
  osConfig,
  ...
}: let
  emacsConfigDir = "${config.xdg.configHome}/emacs";
  c = config.lib.stylix.colors;
in
  lib.optionalAttrs (osConfig.modules.emacs.enable or false) {
    home = {
      sessionPath = ["${emacsConfigDir}/bin"];

      sessionVariables = {
        EMACSDIR = emacsConfigDir;
        DOOMDIR = "${config.xdg.configHome}/doom";
      };

      file = {
        ".config/doom/themes/base16-stylix-theme.el".text = ''
          ;;; base16-stylix-theme.el --- Stylix base16 theme -*- lexical-binding: t; -*-
          ;; Auto-generated by Nix — do not edit manually.
          (require 'base16-theme)
          (defvar base16-stylix-theme-colors
            '(:base00 "#${c.base00}"
              :base01 "#${c.base01}"
              :base02 "#${c.base02}"
              :base03 "#${c.base03}"
              :base04 "#${c.base04}"
              :base05 "#${c.base05}"
              :base06 "#${c.base06}"
              :base07 "#${c.base07}"
              :base08 "#${c.base08}"
              :base09 "#${c.base09}"
              :base0A "#${c.base0A}"
              :base0B "#${c.base0B}"
              :base0C "#${c.base0C}"
              :base0D "#${c.base0D}"
              :base0E "#${c.base0E}"
              :base0F "#${c.base0F}"))
          (deftheme base16-stylix)
          (base16-theme-define 'base16-stylix base16-stylix-theme-colors)
          (provide-theme 'base16-stylix)
          (provide 'base16-stylix-theme)
        '';
      };

      activation.linkEmacsD = lib.hm.dag.entryAfter ["writeBoundary"] ''
        if [ -e "$HOME/.emacs.d" ] && [ ! -L "$HOME/.emacs.d" ]; then
          echo "Refusing to replace non-symlink $HOME/.emacs.d" >&2
          exit 1
        fi
        $DRY_RUN_CMD ln -sfn "${emacsConfigDir}" "$HOME/.emacs.d"
      '';
    };

    # Prevent Stylix from touching programs.emacs — Doom manages its own init
    stylix.targets.emacs.enable = false;
  }
