{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.services.nymvpn;
in {
  options.services.nymvpn = {
    enable = lib.mkEnableOption "the NymVPN daemon and CLI";
  };

  config = lib.mkIf cfg.enable {
    boot.kernelModules = ["tun" "wireguard"];

    # A hard shutdown can leave Nym's static-resolver recovery file behind.
    # Remove it only during boot; Nym may legitimately need it while running.
    systemd.tmpfiles.rules = [
      "r! /etc/resolv.conf.nymbackup - - - - -"
    ];

    environment.systemPackages = [pkgs.nym-vpn-core];

    systemd.services = {
      # A running Nym session can leave resolv.conf temporarily unsigned while
      # switch-to-configuration restarts networking. Recover openresolv's
      # registered NetworkManager state before NixOS adds its static entry.
      network-local-commands.serviceConfig.ExecStartPre = pkgs.writeShellScript "recover-resolvconf-ownership" ''
        current_signature="$(${pkgs.coreutils}/bin/head -n 1 /etc/resolv.conf 2>/dev/null || true)"
        if [ "$current_signature" != "# Generated by resolvconf" ]; then
          ${pkgs.openresolv}/sbin/resolvconf -u
        fi
      '';

      nym-vpnd = {
        description = "NymVPN daemon";
        wantedBy = ["multi-user.target"];
        wants = ["network-pre.target"];
        after = ["network-pre.target" "NetworkManager.service" "systemd-resolved.service"];
        serviceConfig = {
          ExecStart = "${pkgs.nym-vpn-core}/bin/nym-vpnd";
          Restart = "on-failure";
          RestartSec = 5;
          DeviceAllow = ["/dev/net/tun rw"];
          PrivateDevices = false;
        };
      };
    };
  };
}
