# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and maybe overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "virtio_pci"
        "virtio_scsi"
        "ahci"
        "sd_mod"
      ];
      kernelModules = [];
    };
    kernelModules = [];
    extraModulePackages = [];
    kernelParams = ["console=ttyS0,19200n8"];
    loader = {
      systemd-boot.enable = lib.mkForce false;
      grub = {
        forceInstall = true;
        device = "nodev";
        extraConfig = ''
          serial --speed=19200 --unit=0 --word=8 --parity=no --stop=1
          terminal_input serial;
          terminal_output serial;
        '';
      };
      timeout = lib.mkForce 10;
    };
  };

  fileSystems."/" = {
    device = "/dev/sda";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/sdb";}
  ];

  networking = {
    useDHCP = lib.mkForce false;
    defaultGateway = lib.mkForce null;
    interfaces.eth0.useDHCP = lib.mkDefault true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
