name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Run tests
      run: deno test tests/main.ts --allow-read
    - name: Check formatting
      run: deno fmt tests/ --check
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - run: nix flake check
